feat: add remix filter
jakubito/spotify-release-list pull request #31
Opened 2021-12-19 01:12 UTC by schwartzadev

2021-12-21 04:04 UTC, jakubito commented
@schwartzadev please rebase this one too

2021-12-22 01:14 UTC, schwartzadev commented
done!

2022-01-04 10:00 UTC, jakubito requested changes

2022-01-04 10:00 UTC, jakubito commented on src/components/filters/RemixesFilter.js
> + * Render Various Artists filter
Render remixes filter

2022-01-04 10:00 UTC, jakubito commented on src/state/selectors.js
> +    console.log(album.name)
Please remove

2022-03-24 02:53 UTC, jakubito commented
Merged in https://github.com/jakubito/spotify-release-list/commit/552cc4686f2c6dd51396ecad352c7e06426545f8
Thanks

2022-03-24 02:53 UTC, closed without merging